WebReposicion/Models/Reposicion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReposicion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reposicion
    {
        public int NroReposicion { get; set; }
        public string NombreReponedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PrioridadAtencion { get; set; }
        public Nullable<System.DateTime> FechaConfirmacion { get; set; }
    }
}

WebReposicion/Models/ViewModels/ReposicionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebReposicion.Models.ViewModels
{
    public class ReposicionViewModel
    {
        public int NroReposicion { get; set; }
        public string NombreReponedor { get; set; }
        public DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public int PrioridadAtencion { get; set; }
        /*****************************************/
        //public int IdDetalle { get; set; }
        //public int PkArticulo { get; set; }
        //public int Almacen { get; set; }
        //public string CodigoArticulo { get; set; }
        //public string NombreArticulo { get; set; }
        //public string Categoria { get; set; }
        //public int Cantidad { get; set; }
    }

}

WebReposicion/Controllers/ReposicionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReposicion.Models;
using WebReposicion.Models.ViewModels;
using System.Transactions;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

namespace WebReposicion.Controllers
{
    public class ReposicionController : Controller
    {
        // GET: Reposicion
        public ActionResult Index()
        {
            return View();
        }

       
        // CONTROLADORES: Generar pedido de reposición
        public ActionResult GenerarPedido()
        {
           
            List<StockDisponibleViewModel> articulos;
            articulos = null;
            using (DBPREDICTIVOEntities db=new DBPREDICTIVOEntities())
            {
                db.Database.CommandTimeout = 300;
                articulos = (from d in db.sp_ObtenerDisponiblexAlmacen("")
                             select new StockDisponibleViewModel
                             {
                                 Nro = Convert.ToInt32(d.Nro),
                                 Fk_ubicacion = d.FK_UBICACION,
                                 Codigo = d.Codigo,
                                 Descripcion = d.Descripcion,
                                 Categoria = d.Categoria,
                                 Almacen = d.Almacen,
                                 Stock = Convert.ToInt32(d.Stock)

                             }).ToList();

               
            }

            return View(articulos);
            //return Redirect("~/Reposicion/GenerarPedido");
        }


        // GET: Reposicion
        public ActionResult BuscarArticulo()
        {
            return View();
        }





        [HttpGet]
        public ActionResult GenerarPedido(string cadena)
        {
          
            List<StockDisponibleViewModel> articulos;
            using (DBPREDICTIVOEntities db = new DBPREDICTIVOEntities())
            {
                db.Database.CommandTimeout = 300;
                if (cadena != "" || cadena != null)
                {
                    articulos = (from d in db.sp_ObtenerStockDisponiblesxAlmacen(cadena)
                                 select new StockDisponibleViewModel
                                 {
                                     Nro=Convert.ToInt32(d.Nro),
                                     Fk_ubicacion=d.FK_UBICACION,
                                     PkMA=d.FK_MAESTRO_ARTICULOS,
                                     Codigo=d.Codigo,
                                     Descripcion=d.Descripcion,
                                     Categoria=d.Categoria,
                                     Almacen=d.Almacen,
                                     Stock= Convert.ToInt32(d.Stock),
                                     StockSolicitar=0

                                 }).ToList();
                    if (articulos.Count>0)
                    {
                        ViewBag.Confirmacion = "Cargada la disponibilidad de artículos en almacén ...";
                    }

                    // Lista temporal de pedidos
                    List<ReposicionDetViewModel> detallePedido;
                    using (DBPREDICTIVOEntities dba=new DBPREDICTIVOEntities())
                    {
                        //try
                        //{
                        //    var NroReposicion = (from d in db.Reposicion where d.Estado == "TEMPORAL" select d).First();

                            detallePedido = (from d in db.sp_ObtenerPedidoGTemporal(Session["NameUser"].ToString()) 
                                             select new ReposicionDetViewModel
                                             {
                                                 IdDetalle = Convert.ToInt32(d.IdDetalle.Value),
                                                 NroReposicion = (d.NroReposicion.Value),
                                                 PkArticulo = (d.PkArticulo.Value),
                                                 Almacen = d.Almacen.Value,
                                                 CodigoArticulo = d.CodigoArticulo,
                                                 NombreArticulo = d.NombreArticulo,
                                                 Categoria = d.Categoria,
                                                 Cantidad = (d.Cantidad.Value)

                                             }).ToList();

                            if (detallePedido.Count > 0)
                            {

                                ViewBag.NroReposicion = detallePedido.FirstOrDefault().NroReposicion;
                            }

                        //}
                        //catch (Exception)
                        //{


                        //  detallePedido = null;
                        //}
               

                    }

                   ViewBag.ConfirmacionG = Session["ErrorGenerar"];
                    Session["ErrorGenerar"]=null;
                    ViewBag.detallePedido = detallePedido;

                    return View(articulos);
                }

                return Redirect("~/Reposicion/GenerarPedido");
            }

           
        }



        [HttpGet]
        public  ActionResult GenerarTemporal(int PkArticulo, int Fk_ubicacion,string Codigo,string Descripcion,string Categoria, int Stock, int stockSol)
        {

            if (stockSol <= Stock)
            {
                using (TransactionScope registro=new TransactionScope())
                { // Apertura del rollback en el contexto
                   

                    try
                    {
                        using (SqlConnection sqlConnection1 = new SqlConnection(ConfigurationManager.ConnectionStrings["BDPREDICTIVO"].ToString()))
                        {
                            using (SqlCommand cmd = new SqlCommand())
                            {
                                // Sp creado para  cargar los pedidos temporales 
                                cmd.CommandText = "sp_GenerarPedidotemporal";
                                cmd.CommandType = CommandType.StoredProcedure;

                                cmd.Parameters.AddWithValue("@Reponedor", Session["NameUser"].ToString());
                                cmd.Parameters.AddWithValue("@Estado", "TEMPORAL");
                                cmd.Parameters.AddWithValue("@PrioridadAtencion", 1);
                                cmd.Parameters.AddWithValue("@PkArticulo", PkArticulo);
                                cmd.Parameters.AddWithValue("@PkAlmacen", Fk_ubicacion);
                                cmd.Parameters.AddWithValue("@CodigoArticulo", Codigo);
                                cmd.Parameters.AddWithValue("@NombreArticulo", Descripcion);
                                cmd.Parameters.AddWithValue("@Categoria", Categoria);
                                cmd.Parameters.AddWithValue("@Cantidad", stockSol);
                                cmd.Connection = sqlConnection1;
                                sqlConnection1.Open();
                                cmd.ExecuteNonQuery();

                                registro.Complete();
                            }
                        }

                        return Redirect("~/Reposicion/GenerarPedido");

                    }
                    catch (Exception)
                    {
                        registro.Dispose();
                        throw;
                    }
      
                }
            }

            else
            {
                Session["ErrorGenerar"]= "Verifique, la cantidad ingresada no puede ser mayor al stock disponible.";
               
            }
               
           //List<StockDisponibleViewModel> articulos=null;

            return Redirect("~/Reposicion/GenerarPedido");

        }


        [HttpPost]
        public ActionResult ConfirmarPedido(int NroReposicion)
        {
            using (TransactionScope registro = new TransactionScope())
            { // Apertura del rollback en el contexto


                try
                {
                    using (SqlConnection sqlConnection1 = new SqlConnection(ConfigurationManager.ConnectionStrings["BDPREDICTIVO"].ToString()))
                    {
                        using (SqlCommand cmd = new SqlCommand())
                        {
                            // Sp creado para  cargar los pedidos temporales 
                            cmd.CommandText = "sp_ConfirmarPedido";
                            cmd.CommandType = CommandType.StoredProcedure;

                            cmd.Parameters.AddWithValue("@NroReposicion", NroReposicion);
                          
                            cmd.Connection = sqlConnection1;
                            sqlConnection1.Open();
                            cmd.ExecuteNonQuery();

                            registro.Complete();
                        }
                    }
                    ViewBag.Confirmacion = "Se ha generado el pedido en almacenes.";

                    return Redirect("~/Reposicion/GenerarPedido");

                }
                catch (Exception)
                {
                    registro.Dispose();
                    throw;
                }

            }

        }






        // GET: Editar pedido de reposición
        public ActionResult EditarPedido()
        {
            ViewBag.detallePedido = Session["DetallePedidoEdicion"];
            ViewBag.NroRe =Session["NroPedidoEditar"];
            ViewBag.MensajeDetPedido=Session["MensajeDetPedido"];
            Session["MensajeDetPedido"]=null;
            ViewBag.ConfirmarAnulacion = Session["ConfirmarAnulacion"];
            Session["ConfirmarAnulacion"] = null;
            return View();
        }

        public ActionResult ListarPedidoDetEditar(string cadena)
        {
            if (cadena == null || cadena == "")
            {
                cadena = "0";

WebReposicion/Views/Reposicion/BuscarArticulo.cshtml
@model List<WebReposicion.Models.ViewModels.StockDisponibleViewModel>
@{
    ViewBag.Title = "BuscarArticulo";
}


@using (Html.BeginForm("BuscarArticulo", "Reposicion", FormMethod.Get))
{
    <div class="container">
        <div class="modal active" id="modalAdd">
            <div class="modal-dialog modal-lg modal-dialog center-block">
                <div class="modal-content">
                    <div class="modal-header" style="background-color:#3c8dbc">
                        <b style="color:aliceblue">
                            <span class="fa fa-binoculars"> </span> DISPONIBILIDAD PARA REPOSICIÓN
                        </b>
                        <button class="close" data-dismiss="modal">&times;</button>

                    </div>
                    <div class="modal-body">

                        <div style="text-align:left;">
                            @Html.TextBox("cadena", "", new { @class = "form-control", @style = "text-align:left", @placeholder = "INGRESE EL CÓDIGO DEL PRODUCTO PARA INICIAR BUSQUEDA Y AGREGAR" })
                            <br />
                            <input type="submit" class="btn btn-group-lg btn-dropbox" value="Ver disponibilidad" onclick="cargarArticulo" />

                        </div>
                        <br />
                        <div class="row">

                            <div>
                                <table class="table table-hover table-bordered">
                                    <tr style="background-color:lightsteelblue">

                                        <th>#</th>
                                        <th>CÓDIGO</th>
                                        <th>DESCRIPCIÓN</th>
                                        <th>ALMACÉN</th>
                                        <th>STOCK</th>
                                        <th>UNIDADES</th>
                                        <th></th>

                                    </tr>

                                    @foreach (var oElemento in Model)
                                    {
                                        <tr>
                                            @Html.Hidden(oElemento.Fk_ubicacion.ToString())
                                            <td>@oElemento.Nro</td>
                                            <td>@oElemento.Codigo</td>
                                            <td>@oElemento.Descripcion</td>
                                            <td>@oElemento.Almacen</td>
                                            <td>@oElemento.Stock</td>
                                            @*<td> @Html.TextBox("cadena", "", new { @class = "form-control", @style = "text-align:right", @placeholder = "Cantidad" })</td>*@
                                            <td><input type="number"></td>
                                            <td> <button type="submit" class="btn btn-success"> <span class="fa fa-check-circle"> </span></button></td>


                                        </tr>
                                    }
                                </table>
                            </div>

                        </div>


                    </div>

                    <div class="modal-footer">


                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebReposicion/Views/Reposicion/DevolverPedido.cshtml
@{
    /**/

    ViewBag.Title = "Devolver Pedido";
    List<WebReposicion.Models.ViewModels.ArticuloDevViewModel> detallePedido = (List<WebReposicion.Models.ViewModels.ArticuloDevViewModel>)ViewBag.detallePedido;

}

<h3 style="text-align:center;color:dimgrey"><b>  <span class="fa fa-chain-broken"> </span> DEVOLUCIÓN DE ARTÍCULOS</b></h3>

<div class="panel panel-default">
    <div class="panel panel-heading" style="background-color:#3c8dbc">
        <b style="color:aliceblue">  <span class="glyphicon glyphicon-inbox"> </span>  CONSULTAR ARTÍCULO</b>
    </div>

    @using (Html.BeginForm("ObtenerArticuloReponer", "Reposicion", FormMethod.Post))
    {

        <div class="panel-body">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <br />
                <div>@Html.TextBox("cadena", "", new { @class = "form-control", @style = "text-align:right", @placeholder = "INGRESE EL CÓDIGO DEL PRODUCTO PARA INICIAR BUSQUEDA" })</div>


                <br>
                <div style="text-align:right">


                    <button type="submit" class="btn btn-app">
                        <span class="badge bg-green-active"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Iniciar</font></font></span>
                        <i class="fa fa-search"></i><font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                                Buscar producto
                            </font>
                        </font>
                    </button>


                </div>


            </div>
        </div>

    }

</div>


@using (Html.BeginForm("ConfirmarDevolucion", "Reposicion", FormMethod.Get))

{
    <div class="panel panel-default">
        @*<div class="panel panel-heading" style="background-color:#3c8dbc">
                <b style="color:aliceblue">   <span class="glyphicon glyphicon-blackboard"> </span>  Historial del artículo</b>
            </div>*@
        <div class="panel-body">

            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <span class="glyphicon glyphicon-bookmark"> </span>
                    <h3 class="box-title"><b>Detalle del producto </b></h3>
                    <div class="box-tools pull-right">

                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->


                <div>
                    <table id="myTable" class="table table-bordered table-hover table-striped">
                        <tr style="background-color:lightblue;">

                            @*<th>@Html.DisplayNameFor(d => detallePedido.First().NroReposicion)</th>
                                <th>@Html.DisplayNameFor(d => detallePedido.First().PkArticulo)</th>
                                <th>@Html.DisplayNameFor(d => detallePedido.First().Almacen)</th>*@
                            @*<th>@Html.DisplayNameFor(model => model.First().TOTAL_AL_DIA)</th>*@
                            <th>CÓDIGO</th>
                            <th>DESCRIPCIÓN</th>
                            <th>STOCK TDA</th>
                            <th>ALMACÉN</th>
                            <th>UND. DEVOLVER</th>
                        </tr>
                        @if (ViewBag.detallePedido != null)
                        {
                            foreach (var oElemento in detallePedido)
                            {
                                <tr>
                                    @Html.Hidden("Pk_ma", oElemento.Pk_ma)
                                    @Html.Hidden("Pk_ubc", oElemento.Pk_ubc)

                                    <td>@oElemento.Codigo</td>
                                    <td>@oElemento.Descripcion</td>
                                    <td>@oElemento.StockTDA</td>
                                    <td>@oElemento.Almacen</td>
                                    <td>
                                        <input type="number" id="stockDev" name="stockDev" value="@oElemento.Und">
                                    </td>



                                </tr>
                            }
                        }
                    </table>

                </div>

                <div class="box-footer" style="background-color:gainsboro;">

                    <div class="box-tools pull-right">
                        @if (ViewBag.detallePedido != null)
                        {
                            <input type="button" class="btn btn-danger" value="Confirmar devolución" data-toggle="modal" data-target="#modalAdd2" />
                        }
                        else
                        {
                            <input type="button" class="btn btn-danger" value="Confirmar devolución" onclick="cargarArticulo" disabled />
                        }
                        <b></b>
                        <b></b>

                    </div><!-- /.box-tools -->
                </div>

            </div>

        </div>
    </div>



    <div class="container">
        <div class="modal fade" id="modalAdd2" tabindex="-1">
            <div class="modal-dialog modal-sm modal-dialog center-block">
                <div class="modal-content">
                    <div class="modal-header" style="background-color:#3c8dbc">
                        <b style="color:aliceblue">
                            <span class="fa fa-calendar-check-o"> </span> DEVOLUCIÓN DE MERCADERÍA
                        </b>
                        <button class="close" data-dismiss="modal">&times;</button>

                    </div>
                    <div class="modal-body">

                        ¿Desea confirmar la devolución del artículo al almacén?
                        <br />

                    </div>

                    <div class="modal-footer" style="background-color:lightgray">


                        <button type="submit" class="btn btn-danger"> DEVOLVER </button>


                    </div>
                </div>
            </div>
        </div>
    </div>
}



@if (ViewBag.ConfirmarDevolucion != null)
{
    if (ViewBag.ConfirmarDevolucion == "OK")
    {
        <div class="box-footer" style="background-color:aliceblue;">
            <p style="color:green">Devolución correctamente realizada en el sistema.</p>
        </div>
    }
    else
    {
        <div class="box-footer" style="background-color:aliceblue;">
            <p style="color:red">Verificar, la cantidad a devolver es mayor al stock disponible.</p>
        </div>
    }

}

WebReposicion/Views/Reposicion/EditarPedido.cshtml
@{
    ViewBag.Title = "Editar Pedido";
}

<h3 style="text-align:center;color:dimgrey"><b>  <span class="fa fa-pencil-square-o"> </span> EDITAR PEDIDOS</b></h3>

<div class="panel panel-default">
    <div class="panel panel-heading" style="background-color:#3c8dbc">
        <i class="fa fa-search"></i><font style="vertical-align: inherit;"></font>
        @*<b style="color:aliceblue">  <span class="glyphicon glyphicon-inbox"> </span>  Consulta de stock de artículos</b>*@
    </div>
    @using (Html.BeginForm("ListarPedidoDetEditar", "Reposicion", FormMethod.Post))
    {

        <div class="panel-body">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <br />
                <div>@Html.TextBox("cadena", "", new { @class = "form-control", @style = "text-align:right", @type = "number", @placeholder = "INGRESE EL # DEL PEDIDO A EDITAR" })</div>


                <br>
                <div style="text-align:right">


                    <button type="submit" class="btn btn-app">
                        <span class="badge bg-green-active"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Iniciar</font></font></span>
                        <i class="fa fa-search"></i><font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                                Buscar pedido
                            </font>
                        </font>
                    </button>


                </div>
            </div>
        </div>
    }
</div>







<div class="panel panel-default">
    @*<div class="panel panel-heading" style="background-color:#3c8dbc">
            <b style="color:aliceblue">   <span class="glyphicon glyphicon-blackboard"> </span>  Historial del artículo</b>
        </div>*@
    <div class="panel-body">

        <div class="box box-solid box-primary">
            <div class="box-header with-border">
                <span class="glyphicon glyphicon-bookmark"> </span>
                <h3 class="box-title"><b>Lista de productos solicitados - Nro Pedido: @ViewBag.NroRe  </b></h3>
                <div class="box-tools pull-right">

                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->

            <div class="modal-body">



                <br />

                @*@using (Html.BeginForm("Eliminar", "Reposicion", FormMethod.Get))
                    {*@
                <div class="row">

                    <div>
                        <table class="table table-hover table-bordered table-responsive">
                            <tr style="background-color:lightsteelblue">

                                <th>ITEM</th>
                                <th>CÓDIGO</th>
                                <th>ARTÍCULO</th>
                                <th>CATEGORÍA</th>
                                <th>CANTIDAD</th>
                                <th>ALMACÉN</th>
                                <th></th>


                            </tr>
                            @if (ViewBag.detallePedido != null)
                            {

                                List<WebReposicion.Models.ViewModels.ListaPedidoDetViewModel> detallePedido = (List<WebReposicion.Models.ViewModels.ListaPedidoDetViewModel>)ViewBag.detallePedido;



                                foreach (var oElemento in detallePedido)
                                {
                                    <tr>
                                        @*@Html.Hidden("Fk_ubicacion", oElemento.Fk_ubicacion.ToString())
                                            @Html.Hidden("Stock", oElemento.Stock.ToString())

                                            @Html.Hidden("Descripcion", oElemento.Descripcion.ToString())
                                            @Html.Hidden("Categoria", oElemento.Categoria.ToString())*@
                                        @*@Html.Hidden("PkArticulo", oElemento.PkMA.ToString())*@

                                        <td>@oElemento.Nro</td>
                                        <td>@oElemento.CodigoArticulo</td>
                                        <td>@oElemento.NombreArticulo</td>
                                        <td>@oElemento.Categoria</td>
                                        @using (Html.BeginForm("Editar", "Reposicion", FormMethod.Get))
                                        {
                                            @Html.Hidden("Codigo", oElemento.CodigoArticulo.ToString())
                                            <td><input type="number" id="stockSol" name="stockSol" value="@oElemento.Cantidad" style="text-size-adjust:auto"></td>

                                            @*<td> @oElemento.Cantidad</td>*@
                                            <td>@oElemento.Almacen</td>
                                            <td>

                                                <button type="submit" onclick=""><span class="fa fa-floppy-o"> </span></button>
                                                |

                                                <span class="glyphicon glyphicon-trash"> </span>
                                                @Html.ActionLink("Delete", "Eliminar", new { CodigoArticulo = oElemento.CodigoArticulo })



                                            </td>

                                        }
                                    </tr>
                                }
                                Session["DetallePedidoEdicion"] = null;
                            }
                        </table>
                    </div>

                </div>
                @*}*@
            </div>


            <div class="modal-footer">


                @if (ViewBag.MensajeDetPedido != null)
                {
                    <button class="btn btn-danger" disabled>Anular Pedido <span class="fa fa-calendar-times-o"> </span></button>
                }
                else
                {
                    <button class="btn btn-danger" data-toggle="modal" data-target="#modalAdd2">Anular Pedido <span class="fa fa-calendar-times-o"> </span></button>
                }

            </div>



            <div class="box-footer" style="background-color:gainsboro;">

                <div class="box-tools pull-right">
                    @if (ViewBag.MensajeDetPedido != null)
                    {
                        <p style="color:red">@ViewBag.MensajeDetPedido </p>
                    }
                    @if (ViewBag.ConfirmarAnulacion != null)
                    {
                        <p style="color:green"> Se realizo con exito la anulación del Nro de Reposición @ViewBag.NroRe en el sistema. </p>

                    }
                </div><!-- /.box-tools -->
            </div>



        </div>

    </div>
</div>



@*Confirmación de anulación*@
<div class="container">
    <div class="modal fade" id="modalAdd2" tabindex="-1">
        <div class="modal-dialog modal-sm modal-dialog center-block">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#3c8dbc">
                    <b style="color:aliceblue">
                        <span class="fa fa-calendar-check-o"> </span> ANULACIÓN DEL PEDIDO
                    </b>
                    <button class="close" data-dismiss="modal">&times;</button>

                </div>
                <div class="modal-body">

                    ¿Desea anular el pedido registrado?
                    <br />




                </div>

                <div class="modal-footer" style="background-color:lightgray">
                    @using (Html.BeginForm("AnularPedido", "Reposicion", FormMethod.Get))

                    {

                        @*<button class="btn btn-danger"> NO</button>*@
                        <button class="btn btn-danger"> ANULAR <span class="fa fa-calendar-times-o"> </span> </button>

                    }



                </div>
            </div>
        </div>
    </div>
</div>