WebReposicion/Models/ViewModels/KardexViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebReposicion.Models.ViewModels
{
    public class KardexViewModel
    {
        [Display(Name ="Fecha Movimiento")]
        public DateTime FECHA_MOV { get; set; }

        [Display(Name = "Código Artículo")]
        public string COD_ART_IMPORT { get; set; }

        [Display(Name = "Documento operación")]
        public string NUMERO_DOCUMENTO { get; set; }

        [Display(Name = "Cantidad Movimiento")]
        public int CANTIDADES { get; set; }

        [Display(Name = "Stock del día")]
        public int TOTAL_AL_DIA { get; set; }

        [Display(Name = "Descripción Movimiento")]
        public string DESCRIP_MOV { get; set; }

        [Display(Name = "Usuario")]
        public string PC_CLIENTE { get; set; }
    }
}

WebReposicion/Controllers/KardexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReposicion.Models;
using WebReposicion.Models.ViewModels;
using X.PagedList;


namespace WebReposicion.Controllers
{
    public class KardexController : Controller
    {
        // GET: Kardex
        public ActionResult Index()
        {
            List<KardexViewModel> articulos = new List<KardexViewModel>();
            return View(articulos);
        }

        [HttpPost]
        public ActionResult Index(string Cadena,DateTime FechaMov)

        {
            //List<KardexViewModel> articulos = new List<KardexViewModel>();
            
            using (DBPREDICTIVOEntities db = new DBPREDICTIVOEntities())
                          
            {
                db.Database.CommandTimeout = 300;
                int total = 0;
                int totalDia = 0;

                if (Cadena != null)
                {
                 var articulos = (from d in db.sp_ObtenerHistorialKardex(FechaMov, Cadena)
                                 select new KardexViewModel
                                 {
                                     FECHA_MOV = d.FECHA_MOV,
                                     COD_ART_IMPORT = d.COD_ART_IMPORT,
                                     NUMERO_DOCUMENTO = d.NUMERO_DOCUMENTO,
                                     CANTIDADES = d.CANTIDADES,
                                     TOTAL_AL_DIA = Convert.ToInt32(d.TOTAL_AL_DIA),
                                     DESCRIP_MOV = d.DESCRIP_MOV,
                                     PC_CLIENTE = d.PC_CLIENTE


                                 }).ToList();

                    if (articulos.Count()>0)
                    {
                        total = articulos.ElementAt(0).TOTAL_AL_DIA;
                      
                        foreach (var item in articulos)
                        {
                            totalDia = totalDia + item.CANTIDADES;
                        }
                    }
                    totalDia = totalDia + total;
                    ViewBag.StockActual = total;
                    ViewBag.totalDia = totalDia;

                    return View(articulos);
                }

            }
            ViewBag.StockActual = 0;

            return Redirect("~/Kardex/Index");
        }
    }
}

WebReposicion/Views/Kardex/Index.cshtml
@model List<WebReposicion.Models.ViewModels.KardexViewModel>

@{
    ViewBag.Title = "KARDEX DE ARTÍCULO CONSULTADO";
}


<h3 style="text-align:center;color:dimgrey"><B><span class="fa fa-binoculars"> </span>@ViewBag.Title</B></h3>


@using (Html.BeginForm("Index", "Kardex", FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel panel-heading" style="background-color:#3c8dbc">
            <b style="color:aliceblue">  <span class="glyphicon glyphicon-inbox"> </span>  Consulta de historial de movimientos</b>
        </div>
        <div class="panel-body">
            <div class="col-md-3"></div>
            <div class="col-md-6">

                @Html.TextBox("Cadena", "", new { @class = "form-control", @style = "text-align:right", @placeholder = "INGRESE EL CÓDIGO DEL PRODUCTO PARA VER SU HISTORIAL" })
                <br />
                <div style="text-align:right">
                    <input type="date" name="FechaMov" id="FechaMov" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                </div>
                <div style="text-align:right">
                    <br />
                 
                    <button type="submit" class="btn btn-app">
                        <span class="badge bg-green-active"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Iniciar</font></font></span>
                        <i class="fa fa-search-plus"></i><font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                                Buscar producto
                            </font>
                        </font>
                    </button>
                </div>
            </div>



            @*<div>
                    <input type="text" class="form-control" name="Cadena" placeholder="Ingrese nombre del cliente" required autofocus>
                </div>*@


            @*<button id="btnTodo" type="submit" class="btn btn-default" >Cargar todo</button>*@
        </div>
    </div>
}


<div class="panel panel-default">
    @*<div class="panel panel-heading" style="background-color:#3c8dbc">
            <b style="color:aliceblue">   <span class="glyphicon glyphicon-blackboard"> </span>  Historial del artículo</b>
        </div>*@
    <div class="panel-body">

        <div class="box box-solid box-primary">
            <div class="box-header with-border">
                <span class="glyphicon glyphicon-file"> </span>
                <h3 class="box-title"><b>Stock acumulado al iniciar el día:  @ViewBag.StockActual</b></h3>
                <div class="box-tools pull-right">

                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->


            <div>
                <table id="myTable" class="table table-bordered table-hover table-striped">
                    <tr style="background-color:lightblue;">
                        <th>@Html.DisplayNameFor(model => model.First().FECHA_MOV)</th>
                        <th>@Html.DisplayNameFor(model => model.First().COD_ART_IMPORT)</th>
                        <th>@Html.DisplayNameFor(model => model.First().NUMERO_DOCUMENTO)</th>
                        <th>@Html.DisplayNameFor(model => model.First().CANTIDADES)</th>
                        @*<th>@Html.DisplayNameFor(model => model.First().TOTAL_AL_DIA)</th>*@
                        <th>@Html.DisplayNameFor(model => model.First().DESCRIP_MOV)</th>
                        <th>@Html.DisplayNameFor(model => model.First().PC_CLIENTE)</th>

                    </tr>

                    @foreach (var oElemento in Model)
                    {
                        <tr>

                            <td>@oElemento.FECHA_MOV</td>
                            <td>@oElemento.COD_ART_IMPORT</td>
                            <td>@oElemento.NUMERO_DOCUMENTO</td>
                            <td>@oElemento.CANTIDADES</td>
                            @*<td>@oElemento.TOTAL_AL_DIA</td>*@
                            <td>@oElemento.DESCRIP_MOV</td>
                            <td>@oElemento.PC_CLIENTE</td>



                        </tr>
                    }
                </table>

            </div>
            <div class="box-footer" style="background-color:lightblue;">

                <h4 class="box-title"> <span class="glyphicon glyphicon-filter"> </span><b>Stock acumulado al finalizar el día:  @ViewBag.totalDia</b></h4>
                <div class="box-tools pull-right">

                </div><!-- /.box-tools -->
            </div>



        </div>

    </div>
</div>